# feign config
feign:
  compression:
    request:
      enabled: false
      mime-types: text/xml, application/xml, application/json
      min-request-size: 2048
    response:
      enabled: false
  httpclient:
    enabled: true
    connection-timeout: 2000
    max-connections: 200