version: "3"

services:
  id-service:
    restart: always
    image: java:8
    container_name: id-service
    network_mode: host
    working_dir: /data/apps/id-service
    environment:
      TZ: Asia/Shanghai
    command: java -jar /data/apps/id-service/id-service-0.0.1-SNAPSHOT.jar
  sentinel-dashboard:
    restart: always
    image: java:8
    container_name: sentinel-dashboard
    network_mode: host
    working_dir: /data/apps/sentinel-dashboard
    environment:
      TZ: Asia/Shanghai
      server.port: 8858
      project.name: sentinel-dashboard
      sentinel.dashboard.auth.username: sentinel
      sentinel.dashboard.auth.password: sentinel
      sentinel.dashboard.nacos.serverAddr: 127.0.0.1:8844
      sentinel.dashboard.nacos.namespace: 18808baf-2238-4f27-be8b-6cfa3680a0a2
      sentinel.dashboard.nacos.groupId: SENTINEL_GROUP
    command: java -jar /data/apps/sentinel-dashboard/sentinel-dashboard.jar

