version: "3"

services:
  id-service:
    restart: always
    image: java:8
    container_name: id-service
    network_mode: host
    working_dir: /data/apps/id-service
    environment:
      TZ: Asia/Shanghai
      spring.profiles.active: test
    command: java -jar /id-service/id-service-0.0.1-SNAPSHOT.jar
    volumes:
      - /data/apps/id-service:/id-service
  sentinel-dashboard:
    restart: always
    image: java:8
    container_name: sentinel-dashboard
    network_mode: host
    working_dir: /data/apps/sentinel-dashboard
    environment:
      TZ: Asia/Shanghai
      server.port: 8858
      project.name: sentinel-dashboard
      sentinel.dashboard.auth.username: sentinel
      sentinel.dashboard.auth.password: sentinel
      sentinel.dashboard.nacos.serverAddr: 192.168.47.112:8844
      sentinel.dashboard.nacos.namespace: 960c12f6-0adc-4b2b-ac5e-83aee6f3a392
      sentinel.dashboard.nacos.groupId: SENTINEL_GROUP
    command: java -jar /sentinel-dashboard/sentinel-dashboard.jar
    volumes:
      - /data/apps/sentinel-dashboard:/sentinel-dashboard

